apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
  labels:
    app: kube
spec:
  replicas: 3 # Adjust this depending on resource limits and expected load
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: jolenechong/urlshortener:latest
        ports:
        - containerPort: 3001
        imagePullPolicy: Never
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kube
  labels:
    app: kube
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: kube
  type: LoadBalancer